### ISSUE TITLE
msatcommander does not generate required file

### ISSUE THREAD

**Issue by patrick-douglas** [jh041/SamGate#1]
which version of **msatcoomander** should I use to generate required files for SAMGATE script?
I'm currently using version  `msatcommander-0.8.2` and `primer3-2.3.7`

**Comment by jh041** [comment]
I use msatcommander 1.0.8 -beta on a mac. If I recall, the linux version of msatcommander doesn't output everything you need to run the script. So you might need to find a mac machine to do this.

**Comment by patrick-douglas** [comment]
I'm using MSATCOMMANDER in OSX now. which option should I used?
